/**
 * Cross-language parity: app/js/gating.js must agree with ml/src/gating.py.
 *
 * Two implementations of the same arithmetic drift apart the moment one is
 * edited. This test compares them on tiles generated by PYTHON and handed to
 * JS, so there is exactly one tile generator and no possibility of the two
 * languages disagreeing about the input. That matters: the first version of
 * this test reimplemented the RNG in both languages, the two implementations
 * consumed the random stream in different orders, and every comparison failed
 * for reasons that had nothing to do with the gate.
 *
 * Run:  node tools/gating_parity.js
 */

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const Gating = require("../js/gating.js");
const ROOT = path.resolve(__dirname, "..", "..");
const TILE_W = 256, TILE_H = 64;

// Generate tiles in Python (the reference implementation) and serialise them.
const helper = `
import sys, json, base64
import numpy as np
sys.path.insert(0, "ml/src")
import capture, gating

# Real capture-profile tiles, not synthetic blobs: this is the distribution the
# gate actually has to separate, and using it means the test would catch a
# mis-calibration rather than merely a sign error.
tiles = []
for name, params in capture.CAPTURE_PROFILES.items():
    for band in range(3):
        ds = 123 * 7919 + abs(hash(name)) % 100003 + band
        lines, _ = capture.DOCS[band % 3]
        clean = capture.render_document(lines, seed=ds)
        deg = capture.apply_profile(clean, seed=ds, **params)
        y0 = 100 + band * 64
        if y0 + 64 > deg.size[1]:
            break
        g = gating.to_gray(deg.crop((48, y0, 48 + 256, y0 + 64)))
        tiles.append({
            "profile": name,
            "data": base64.b64encode(g.tobytes()).decode(),
            "py_weight": gating.degradation_weight(g),
            "py_sharp": gating.sharpness(g),
        })
print(json.dumps(tiles))
`;

console.log("generating reference tiles in Python ...");
fs.mkdirSync(path.join(ROOT, "artifacts"), { recursive: true });
const tmp = path.join(ROOT, "artifacts", "_gating_parity_tiles.py");
fs.writeFileSync(tmp, helper);
let tiles;
try {
  const out = execFileSync("bash", ["-c",
    `env -u PYTHONPATH -u VIRTUAL_ENV -u PYTHONHOME ./.venv/bin/python ${tmp}`],
    { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  tiles = JSON.parse(out.trim().split("\n").pop());
} finally {
  if (fs.existsSync(tmp)) fs.unlinkSync(tmp);
}

console.log(`${tiles.length} tiles from ${new Set(tiles.map(t => t.profile)).size} profiles\n`);

let pass = 0, fail = 0;
const rows = [];
for (const t of tiles) {
  const buf = Buffer.from(t.data, "base64");
  // Buffer.from(base64) does NOT guarantee 4-byte alignment, and a Float32Array
  // view onto a misaligned offset silently produces garbage on some engines.
  // Copy into a fresh, guaranteed-aligned buffer before viewing. (The first
  // version of this test skipped the copy and every sharpness value came out
  // ~7x too low, which is exactly the kind of bug this test exists to catch.)
  const aligned = new Float32Array(buf.length / 4);
  aligned.set(new Float32Array(buf.buffer, buf.byteOffset, buf.length / 4));
  const g = aligned;
  const jsWeight = Gating.weightFromGray(g, TILE_W, TILE_H);
  const jsSharp = Gating.sharpness(g, TILE_W, TILE_H);
  const dw = Math.abs(jsWeight - t.py_weight);
  const ds = Math.abs(jsSharp - t.py_sharp);
  const ok = dw <= 1e-4 && ds <= 1e-3;
  ok ? pass++ : fail++;
  rows.push({ profile: t.profile, py: t.py_weight, js: jsWeight, ok });
  if (!ok) {
    console.log(`  FAIL  ${t.profile.padEnd(16)} weight py ${t.py_weight.toFixed(4)} ` +
                `js ${jsWeight.toFixed(4)} (D ${dw.toExponential(1)})  ` +
                `sharp py ${t.py_sharp.toFixed(5)} js ${jsSharp.toFixed(5)} (D ${ds.toExponential(1)})`);
  }
}

// Grouped view: one line per profile makes the pattern obvious.
const byProfile = {};
for (const r of rows) (byProfile[r.profile] ||= []).push(r);
console.log("\nper-profile mean weights (python vs javascript):");
for (const [p, rs] of Object.entries(byProfile)) {
  const m = (k) => rs.reduce((a, r) => a + r[k], 0) / rs.length;
  console.log(`  ${p.padEnd(16)} py ${m("py").toFixed(4)}   js ${m("js").toFixed(4)}` +
              `   ${rs.every(r => r.ok) ? "ok" : "MISMATCH"}`);
}

console.log(`\n${pass} passed, ${fail} FAILED`);
process.exit(fail ? 1 : 0);
